config/routes.rb
Rails.application.routes.draw do
  
  resources :posts
  resources :visitors
  
  match '/contacts',     to: 'contacts#new',             via: 'get'
  match '/contacts',     to: 'contacts#create',          via: 'post'
  resources "contacts", only: [:new, :create]

  get 'posts/index'

  get 'posts/show'
  
  get 'products/:id', to: 'products#show', :as => :products

  resources :users
    
  resources :payments do
    member do
      get 'alice_step_1'
      get 'alice_step_11'
    end
  end
    
  resources :payment_requests do
    member do
      get 'bob_step_2'
      get 'complete'
      patch 'broadcast'
    end
  end
  
  root to: 'visitors#index'
  
  get '/auth/:provider/callback' => 'sessions#create'
  get '/signin' => 'sessions#new', :as => :signin
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/auth/failure' => 'sessions#failure'
  
end

app/controllers/payment_requests_controller.rb
class PaymentRequestsController < ApplicationController
  
  respond_to :html, :json
  
  include Crypto # module in /lib
  require 'btcruby/extensions'
  require 'rest-client'

  def index
    @payment_requests = PaymentRequest.where.not(:key_path => nil).page(params[:page]).order(created_at: :desc) 
    respond_with(@payment_requests)
  end
  
  
  def new
    @payment_request = PaymentRequest.new
    # @payment_request.expiry_date  ||= Time.now.utc  # will set the default value only if it's nil
    @payment_request.r = Random.new.bytes(32).unpack('H*')[0].to_i(16) # 256-bit random integer
    @payment_request.blinding_factor = Random.new.bytes(32).unpack('H*')[0].to_i(16) # 256-bit random integer
    real_indices = []
    prng = Random.new
    while real_indices.count < 42
      j = prng.rand(0..83)
      unless real_indices.include? j
        real_indices << j
      end
    end
    @payment_request.real_indices = real_indices.sort

    salt = Figaro.env.tumblebit_salt
    index = (salt.to_i + prng.rand(0..99999)) % 0x80000000
    @payment_request.key_path = "1/#{index}"
  end
  
  
  def create
    @payment_request = PaymentRequest.new(payment_request_params)
    puts "#{payment_request_params}"
    # create @payment_request on Tumbler side
    response= RestClient.post $TUMBLER_PAYMENT_REQUEST_API_URL, {payment_request: {bob_public_key: @payment_request.bob_public_key}}
    result = JSON.parse(response.body)

    # get Tumbler key in http response and save it to @payment_request in Bob wallet
    if valid_pubkey?(result["tumbler_public_key"])
      @payment_request.tumbler_public_key = result["tumbler_public_key"]
      @payment_request.expiry_date = result["expiry_date"]
      @payment_request.request_created # update state from "started" to "step1"
      if @payment_request.save
        flash[:notice] = "Payment Request was successfully created"
        render "show"
      else
        flash[:alert] = "There was a problem with this payment request creation."
        redirect_to payment_requests_url
      end
    else
      flash[:alert] = "Invalid Tumbler public key."
      redirect_to payment_requests_url
    end
    
  end
  
  
  def show
    @payment_request = PaymentRequest.find(params[:id])
    response= RestClient.get($TUMBLER_PAYMENT_REQUEST_API_URL + "/#{@payment_request.bob_public_key}")
    result = JSON.parse(response.body)
    if @payment_request.tumbler_public_key == result["tumbler_public_key"]
      respond_with(@payment_request)
    else
      flash[:alert] = "This payment request seems to be unknown from the Tumbler or the Tumbler API is down."
      redirect_to payment_requests_url
    end
  end
  

  def edit
    @payment_request = PaymentRequest.find(params[:id])
    respond_with(@payment_request)
  end
  

  def update
    @payment_request = PaymentRequest.find(params[:id])
    @payment_request.update_attributes(payment_request_params)
    @notice = ""
    
    unless valid_pubkey?(@payment_request.tumbler_public_key)
      @notice << "Invalid Tumbler Public Key. "
    end
        
    if @notice.blank?
      # TODO: when puzzle solution is saved, lauch the "complete" method
      if @payment_request.aasm_state == "step10"
        blinding_factor = @payment_request.blinding_factor.to_i
        epsilon = @payment_request.solution.to_i(16)/blinding_factor
        puts "Epsilon= #{epsilon.to_s(16)}"
        @payment_request.escrow_tx_broadcasted # transition payment request state from "step10" to "step12"
        @payment_request.puzzle_solution_received # transition payment request state from "step12" to "completed"
        @payment_request.save
        redirect_to @payment_request, notice: 'Puzzle solution was successfully saved.'
      else
        flash[:notice] = "Payment request was successfully updated."
        respond_with(@payment_request)
      end
    else
      redirect_to @payment_request, alert: @notice
    end
  end # of update method
  
  
  def destroy
    @payment_request = PaymentRequest.find_by_id(params[:id])
    if !@payment_request.funded?
      @payment_request.destroy
      redirect_to payment_requests_path, notice: 'Payment request was successfully deleted.'
    else
      redirect_to @payment_request, alert: 'Payment request was funded, it cannot be deleted.'
    end
  end
  
  
  def bob_step_2
    # Steps 2 through 10 in Tumbler-Bob interactions, performed by Bob
    # step2: Bob generates 42 “real” payout addresses (keeps them secret for now) and prepares 42 distinct “real” transactions.
    @payment_request = PaymentRequest.find(params[:id])
    @funded_address = @payment_request.hash_address

    response= RestClient.get($TUMBLER_PAYMENT_REQUEST_API_URL + "/#{@payment_request.bob_public_key}")
    result = JSON.parse(response.body)
    @payment_request.tx_hash = result["utxo"]["tx_hash"]
    @payment_request.index = result["utxo"]["index"]
    @payment_request.amount = result["utxo"]["amount"]
    @payment_request.confirmations = result["utxo"]["confirmations"]
    @payment_request.escrow_tx_received # transition in state machine from "step1" to "step2"
    @payment_request.save

    if @payment_request.beta_values.blank?

      beta = []
      @payment_request.real_indices.each do |i|
        beta[i] = @payment_request.real_btc_tx_sighash(i)
      end
    
      # In Step 3, Bob picks a random secret 256-bit blinding factor r and prepares 42 “fake” transactions.
      # Fake transaction i pays Tumbler compressed Bitcoin address 1 BTC in output 0 
      # with an OP_RETURN output (output 1) bearing r || i. 
      # No network fee is implied in the fake transaction.

      for i in 0..83
        unless @payment_request.real_indices.include? i
          beta[i] = @payment_request.fake_btc_tx_sighash(i)
        end
      end
      # save 84 beta values for Tumbler
      @payment_request.beta_values = beta
      @payment_request.save
    end
      
    # update Tumbler payment request with beta values
    @payment_request.reload
    response= RestClient.patch $TUMBLER_PAYMENT_REQUEST_API_URL, {payment_request: {bob_public_key: @payment_request.bob_public_key, beta_values: "#{@payment_request.beta_values}"}}
    result = JSON.parse(response.body)
    # get c values from result params and put them in an array
    @c_values = Array.new
    @c_values = result["c_values"]
    @payment_request.c_values = @c_values
    @z_values = Array.new
    @z_values = result["z_values"]
    @payment_request.z_values = @z_values
    
    true_count=0
    for i in 0..83
      if @payment_request.beta_values[i] == result["beta_values"][i]
        true_count += 1
      else
        puts @payment_request.beta_values[i]
        puts result["beta_values"][i]
      end
    end
      
    if true_count == 84
      @payment_request.beta_values_sent # update state from "step2" to "step4"
      
      # step6, identify fake set: reveal real indices to Tumbler
      response= RestClient.patch $TUMBLER_PAYMENT_REQUEST_API_URL, {payment_request: {bob_public_key: @payment_request.bob_public_key, real_indices: "#{@payment_request.real_indices}"}}
      result = JSON.parse(response.body)
      
      @payment_request.c_z_values_received # update state from "step4" to "step6"
      @payment_request.real_indices_sent # update state from "step6" to "step7"
      @payment_request.save
      
      # step8, check fake set: check fake epsilon values sent by Tumbler
      @funded_address = @payment_request.hash_address
      @fake_epsilon_values = []
      @fake_epsilon_values = result["fake_epsilon_values"]
      @quotients = []
      @quotients = result["quotients"]
      @payment_request.quotients = @quotients
      @payment_request.save

      # Bob computes sigmai = Dec(epsiloni, ci) for the 42 fake epsilon values
      @sigma = []
      @beta = []
      j = 0
      check_ok = false
      rsa_puzzle_ok = false

      for i in 0..83
        unless @payment_request.real_indices.include? i
          key_hex = @fake_epsilon_values[j]
          iv_hex = $AES_INIT_VECTOR
          key = key_hex.htb
          iv = iv_hex.htb
          decipher = OpenSSL::Cipher::AES256.new(:CBC)
          decipher.decrypt
          decipher.key = key
          decipher.iv = iv
          @sigma[j] = decipher.update(@c_values[i].from_hex) + decipher.final
          
          # Bob checks that @fake_epsilon_values[j] < n  (RSA modulus)
          e = $TUMBLER_RSA_PUBLIC_EXPONENT
          n = $TUMBLER_RSA_PUBLIC_KEY
          rsa_puzzle_ok = (@fake_epsilon_values[j].to_i(16) < n)
          # Bob checks that RSA puzzle zi = (εi)**e
          rsa_puzzle_ok = rsa_puzzle_ok and (@z_values[i] == mod_pow(@fake_epsilon_values[j].to_i(16),e,n).to_s(16))
          
          # Validate promise @c_values[i]: Bob checks that sigmai is a valid ECDSA signature against PKT and betai
          # @tumbler_key = BTC::Key.new(wif: Figaro.env.tumbler_funding_priv_key)
          # @beta[j] = @payment_request.fake_btc_tx_sighash(i)
          # check_ok = @tumbler_key.verify_ecdsa_signature(@sigma[j], @beta[j].htb)  # result must equal true
          if rsa_puzzle_ok # and check_ok
            j += 1
          else
            puts'There is a problem with Tumblers fake epsilons: Bob should abort protocol.'
            return
          end
        end
      end
      if j == 42 and @payment_request.quotients_ok?
        @payment_request.epsilon_values = @fake_epsilon_values
        @payment_request.fake_epsilons_received # update state from "step7" to "step8"
        @payment_request.quotients_received # update state from "step8" to "step10"
        @payment_request.save
        redirect_to @payment_request, notice: 'Bob steps 2, 3, 4, 6, 8 and 10 completed successfully.'
      else
        redirect_to root_url, alert: 'There is a problem with Tumblers fake epsilons: protocol aborted'
      end
    else
      redirect_to root_url, alert: 'Tumbler seems to have wrong beta values or to be down.'
    end
  end # of bob_step_2
  
  

app/views/payment_requests/_form.html.erb
<%= form_for(@payment_request, multipart: true) do |f| %>
  <% unless @payment_request.title %>
  <div class="field">
    <p><%= f.label 'Title' %></p>
    <p><%= f.text_field :title %></p>
  </div>
  <% end %>
<p>Timelocked Escrow Transaction Script:</p>
	<div><pre style="width:600px"><code id="contrat"><%= @payment_request.description %></code></pre></div>
</br><div id="subFormLine1">The P2SH address corresponding to this script shall be funded by Tumbler.</div>
	<div id="subFormLine1">A transaction spending from this address cannot be included in a block until the set date and time has passed.</div>
	<div id="subFormLine2">We can be reasonably certain that any block in the chain was created within approximately two hours of the block’s timestamp.</div>
</br>
	
	<% if @payment_request.id %>
		<%= f.submit 'Update Payment Request with parameters', :class => "btn btn-primary" %>
	<% else %>
	<% @payment_request.real_indices.each do |real| %>
	    <%= f.hidden_field :real_indices, :multiple => true, :value => real %>
	<% end %>
	<%= f.hidden_field :key_path , :value => @payment_request.key_path %>
	<%= f.hidden_field :r , :value => @payment_request.r %>
	<%= f.hidden_field :blinding_factor , :value => @payment_request.blinding_factor %>
	  <p><strong>Lock Time</strong></p>
		<% if @payment_request.expiry_date %>
			<p>Lock Time: <%= @payment_request.expiry_date %></p>
		<% else %>
			<p>Lock Time shall be set by Tumbler.</p>
		<% end %>
		<%= f.submit 'Start Request Creation', :class => "btn btn-primary" %>
	<% end %>
	 | <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
        payment_requests_path, :class => 'btn' %>
<% end %>
</br>
<script>
var ready;
ready = function() {

	var codeSnippet = $('#snippet').data('code');
	var element = document.getElementById("contrat");
	
	var form_field_value = $("#script_category").val()
	
	switch (form_field_value) {

		case "tumblebit_puzzle":
			select = document.getElementById("subFormLine1");
			if (select) {
				select.innerHTML="In the Tumblebit puzzle solving protocol, Alice pays Bob through Tumbler, a trustless intermediary.";
						}
			select = document.getElementById("subFormLine2");
			if (select) {
				select.innerHTML="The script is funded by Alice and can be spent to pay Bob if signed by Tumbler, knowing all ki, pre-images of hi, for i in 1..15.";
						}
			codeSnippet = "IF&#10;RIPEMD160  &#60;h1&#62; EQUALVERIFY&#10;...&#10;RIPEMD160  &#60;h15&#62; EQUALVERIFY&#10;&#60;TumblerPubkey&#62;CHECKSIG&#10;ELSE&#10;&#60;expiry time&#62; CHECKLOCKTIMEVERIFY DROP &#60;AlicePubkey&#62; CHECKSIG&#10;ENDIF";
			break;
		case "tumblebit_escrow_contract":
			select = document.getElementById("subFormLine1");
			if (select) {
				select.innerHTML="A transaction spending from this address cannot be included in a block until the set date and time has passed, unless the 2 required signatures are provided.";
				}
			select = document.getElementById("subFormLine2");
			if (select) {
				select.innerHTML="After the set date and time has passed, the Tumbler's signature is sufficient to move the funds.";
				}
		    codeSnippet = "IF&#10;2 &#60;Tumbler&#62;&#60;Bob&#62; 2 CHECKMULTISIG&#10;ELSE&#10;&#60;expiry time&#62; CHECKLOCKTIMEVERIFY DROP&#10;&#60;Tumbler&#62; CHECKSIG&#10;ENDIF";
		
	}
	element.innerHTML = codeSnippet;
	console.log(codeSnippet);
	console.log(form_field_value);
};

$(document).ready(ready);
</script>

app/views/payment_requests/_payment_request.html.erb
<td><%= link_to payment_request.title, payment_request %></td>
<td><%= payment_request.hash_address %></td>
<td><%= payment_request.aasm_state %></td>
<td><%= link_to "Edit", edit_payment_request_path(payment_request), :class => 'btn btn-xs btn-success' %></td>
<td><%= link_to "Delete", payment_request_path(payment_request), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'btn btn-xs btn-danger' %></td>

app/views/payment_requests/edit.html.erb
<div class="container">
  <div class="row">
	<h1>Edit Payment Request # <%= @payment_request.id if @payment_request %>: <%= @payment_request.title if @payment_request %></h1>

	<div><pre style="width:600px"><code><%= @payment_request.description %></code></pre></div>
	<%= form_for(@payment_request, multipart: true) do |f| %>
	<div class="field">
    <p><%= f.label 'Title' %></p>
    <p><%= f.text_field :title %></p>
  	</div>
	<div class="field">
		<p><%= f.label 'Bob (compressed) Public Key' %></br>
		<%= f.text_field :bob_public_key, :style => "width:540px;", :placeholder => "02BE332AE534CC30FB84BA64817A748DBC9A9C9021463A645F5B3CF2AB4AEB0284" %></p>
	</div>
	
	<div class="field">
		<p><%= f.label 'Tumbler (compressed) Public Key' %></br>
		<%= f.text_field :tumbler_public_key, :style => "width:540px;", :placeholder => "02BE332AE534CC30FB84BA64817A748DBC9A9C9021463A645F5B3CF2AB4AEB0284" %></p>
	</div>
	
	<div class="field">
    <p><%= f.label 'Expiry' %></p>
	<p>Present Time: <%= Time.now.strftime("%Y-%b-%d - %H:%M") %></p>
    <p><%= f.datetime_select(:expiry_date, {:start_year => Date.today.year, :end_year => 2024, :default => @payment_request.expiry_date, :use_two_digit_numbers => true, :prompt => {:day => "day", :month => "month", :year => "year", :hour => "hour", :minute => "minute"}}, {:style => "width: 80px;"}) %></p>
  </div>
	
	<%= f.submit 'Update Payment Request with parameters', :class => "btn btn-primary" %> |<%= link_to "Cancel", @payment_request %>

	<% end %>
</br>
   </div>
</div>

app/views/payment_requests/index.html.erb
<div class="container">
  <div class="row">
    <h3>Payment Requests</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @payment_requests.each do |payment_request| %>
            <tr>
              <%= render payment_request %>
            </tr>
          <% end %>
        </tbody>
      </table>
	  <div class="apple_pagination">
		<%= will_paginate @payment_requests %>
	  </div>
    </div>
  </div>
</div>

app/views/payment_requests/new.html.erb
<%- model_class = PaymentRequest -%>
<div style="padding-left: 20px" >

<h3>Request a New Payment</h3>

<%= render 'form' %>

</div>

app/views/payment_requests/show.html.erb
<div class="container">
  <div class="row">
	<h3>Payment Request # <%= @payment_request.id if @payment_request %>: <%= @payment_request.title if @payment_request.title %></h3>
	<p>Script:</p><pre style="width:600px"><code><%= @payment_request.description if @payment_request %></code></pre>

	<p>Bob (Compressed) Public Key: <strong><%= @payment_request.bob_public_key %></strong></p>
	
	<% if @payment_request.tumbler_public_key.blank? %>
	<%= form_for(@payment_request, multipart: true) do |f| %>
	<table class="table">
    	<tbody>
  		<tr>
			<td><div class="field">
				<p><%= f.label 'Tumbler (compressed) Public Key' %></br>
				<%= f.text_field :tumbler_public_key, :style => "width:540px;", :placeholder => "02BE332AE534CC30FB84BA64817A748DBC9A9C9021463A645F5B3CF2AB4AEB0284" %></p>
			</div></td>
		</tr>
		<tr>
			<td><div class="field">
		    <p><%= f.label 'Expiry' %></p>
			<p>Present Time: <%= Time.now.strftime("%Y-%b-%d - %H:%M") %></p>
		    <p><%= f.datetime_select(:expiry_date, {:start_year => Date.today.year, :end_year => 2024, :default => @payment_request.expiry_date, :use_two_digit_numbers => true, :prompt => {:day => "day", :month => "month", :year => "year", :hour => "hour", :minute => "minute"}}, {:style => "width: 80px;"}) %></p>
		  </div></td>
		</tr>
		<tr>
  			<td><div class="actions">
    		<%= f.submit "Add Tumbler's Public Key", :class => "btn btn-primary" %>
			<%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                payment_requests_path, :class => 'btn' %></div></td>
  		</tr>
	<% end %>
    	</tbody>

	</table>
	<% else %>
		<p>Expiry: <strong><%= Time.at(@payment_request.expiry_date.to_time.to_i).utc %></strong></br>
		Expiry in seconds since epoch time (1/1/1970): <%= @payment_request.expiry_date.to_time.to_i %></p>
		<p>Tumbler (Compressed) Public Key: <strong><%= @payment_request.tumbler_public_key %></strong></p>
		<p>Payment Request Escrow Address to be funded by Tumbler: <strong><%= @payment_request.hash_address %></strong></p>
		<p>Payment Request State: <strong><%= @payment_request.aasm_state %></strong></p>
		<% if @payment_request.aasm_state == "step1" or @payment_request.aasm_state == "step2" %>
			<% if @payment_request.funded? %>
				<p><%=link_to "Submit Request to Tumbler", bob_step_2_payment_request_path(@payment_request), :class => "btn btn-primary" %> | <%= link_to t('.cancel', :default => t("helpers.links.cancel")), payment_requests_path, :class => 'btn' %></p>
			<% end%>
		<% end %>
		<% if @payment_request.aasm_state == "step7" %>
			<p>Bob Real Indices: <pre style="width:600px"><code><%= @payment_request.real_indices if @payment_request %></code></pre></p>
		<% end %>
		<% if @payment_request.aasm_state == "step10" %>
			<p>Puzzle y sent to Alice: <pre style="width:600px"><code><%= @payment_request.y %></code></pre></p>
		<% end %>		
		
		<% if @payment_request.aasm_state == "step10" %>
			<% if @payment_request.solution %>
				<p>Puzzle solution: <strong><%= @payment_request.solution %></strong></p>
				<p><%=link_to "Bob Checks Puzzle Solution", complete_payment_request_path(@payment_request), :class => "btn btn-primary" %> | <%= link_to t('.cancel', :default => t("helpers.links.cancel")), payment_requests_path, :class => 'btn' %></p>
			<% else %>
			<%= form_for(@payment_request, multipart: true) do |f| %>
			<table class="table">
		    	<tbody>
		  		<tr>
					<td><div class="field">
						<p><%= f.label 'Puzzle solution received from Alice' %></br>
						<%= f.text_field :solution, :style => "width:950px;", :placeholder => "52f4b8903ad62f13d0e3402947805f811e6d0b8078c88ea41495ed2193ab1867d6f388c11fb70454c7405e7052ea4795a419863abbadffc2e368e111341f2fb0" %></p>
					</div></td>
				</tr>
				<tr>
		  			<td><div class="actions">
		    		<%= f.submit "Check solution", :class => "btn btn-primary" %> | 
					<%= link_to t('.cancel', :default => t("helpers.links.cancel")),
		                payment_requests_path, :class => 'btn' %></div></td>
		  		</tr>
			<% end %>
		    	</tbody>

			</table>
			<% end%>
		<% end %>
		
		<% if @payment_request.aasm_state == "completed" %>
			<p>Payout address: <strong><%= @payment_request.payout_address(@payment_request.real_indices.first) %></strong></p>
			<p>Payout Tx:</p> <pre style="width:600px"><code><%= @payment_request.payout_tx %></code></pre>
		<% end %>
		
	<% end %>

	

	</div>
</div>

app/views/payment_requests/show_failed_broadcast_tx.html.erb
<div class="container">
  <div class="row">
	<% if @payment_request.signed_tx %>
	<p>Copy the signed transaction below then paste it to <a href="https://coinb.in/#broadcast" target="blank">coinb.in</a> or use Bitcoin Core sendrawtransaction command.</p>
		<p>Raw Signed Transaction:<pre style="width:600px"><code><%= @payment_request.signed_tx %></code></pre></p>
	<% end %>
	</div>
</div>

app/views/payment_requests/sign_tx.html.erb
<div class="container">
  <div class="row">
	<h3>Payout Transaction for <%= @payment_request.title if @payment_request.title %></h3>
	<p>Script:</br><pre style="width:600px"><code> <%= @payment_request.description if @script %></code></pre></p>

	<p>Expiry: <%= Time.at(@payment_request.expiry_date.to_time.to_i).utc %></p>

		<p>Bob (Compressed) Public Key: <%= @payment_request.bob_public_key %></p>
		<p>Tumbler (Compressed) Public Key: <%= @payment_request.tumbler_public_key %></p>
		<p><strong>Tumbler Encrypted Signature</strong>: <pre style="width:600px"><code></code></pre></p>
		<p><strong>Puzzle y</strong>:<pre style="width:600px"><code></code></pre></p>
		<p><strong>Tumbler RSA Public Key</strong>:<pre style="width:600px"><code><%= $TUMBLER_RSA_PUBLIC_KEY %></code></pre></p>
	
	<p>P2SH Address: <strong><%= @payment_request.hash_address if @payment_request %></strong></p>
	<p>Unspent Output (Tx_id:index):  <%= @payment_request.tx_hash if @payment_request %> : <%= @payment_request.index if @payment_request %></br>
	<p>Amount: <%= @payment_request.amount if @payment_request %></br>
	<p>Tumbler's Refund Address: <%= @payment_request.refund_address if @payment_request %></p>

	<p>Redeem Script:<pre style="width:600px"><code><%= @redeem_script %></code></pre></p>

   </div>
</div>
</br>