config/routes.rb
Rails.application.routes.draw do
  
  resources :posts
  resources :visitors
  
  match '/contacts',     to: 'contacts#new',             via: 'get'
  match '/contacts',     to: 'contacts#create',          via: 'post'
  resources "contacts", only: [:new, :create]

  get 'posts/index'

  get 'posts/show'
  
  get 'products/:id', to: 'products#show', :as => :products

  resources :users
    
  resources :payments do
    member do
      get 'alice_step_1'
      get 'alice_step_11'
    end
  end
    
  resources :payment_requests do
    member do
      get 'bob_step_2'
      get 'complete'
      patch 'broadcast'
    end
  end
  
  root to: 'visitors#index'
  
  get '/auth/:provider/callback' => 'sessions#create'
  get '/signin' => 'sessions#new', :as => :signin
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/auth/failure' => 'sessions#failure'
  
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  # skip_before_action :verify_authenticity_token
  include Crypto # module in /lib
  # include Http # module in /lib
  # require 'csv'
  require 'btcruby/extensions'
  # require 'mechanize'
  require 'rest-client'
  # require 'digest'
  
  def index
    @payments = Payment.where.not(:key_path => nil).page(params[:page]).order(created_at: :desc)
  end
  
  
  def new
    @payment = Payment.new
    # @payment.expiry_date ||= Time.now.utc  # will set the default value only if it's nil
    real_indices = []
    prng = Random.new
    while real_indices.count < 15
      j = prng.rand(0..299)
      unless real_indices.include? j
        real_indices << j
      end
    end
    @payment.real_indices = real_indices.sort
    
    salt = Figaro.env.tumblebit_salt
    index = (salt.to_i + prng.rand(0..99999)) % 0x80000000
    @payment.key_path = "1/#{index}"
  end
  
  
  def create
    @payment = Payment.new(payment_params)
    
    # create @payment on Tumbler side
    response= RestClient.post $TUMBLER_PAYMENT_API_URL, {payment: {alice_public_key: @payment.alice_public_key}}
    result = JSON.parse(response.body)
    # get Tumbler key in http response and save it to @payment in Alice wallet
    @payment.tumbler_public_key = result["tumbler_public_key"]
    @payment.expiry_date = result["expiry_date"]
    
    if @payment.save
      flash[:notice] = "Payment was successfully created"
      render "show"
    else
      flash[:notice] = "There was a problem with this payment creation."
      redirect_to payments_url
    end
  end
  
  
  def show
    @payment = Payment.find(params[:id])
    if @payment.aasm_state == "step8"
      alice_step_11
    end
  end
  
  
  def edit
    @payment = Payment.find(params[:id])
  end
  
  
  def update
    @payment = Payment.find(params[:id])
    if @payment.update_attributes(payment_params)
      if @payment.y and @payment.aasm_state == "initiated"
        @payment.y_received # update state from "initiated" to "step1"
        @payment.save
      end
      if @payment.aasm_state == "step1"
        alice_step_1
      else
        flash[:notice] = "Payment successfully updated."
        render "show"
      end
    else
      flash[:notice] = "There was a problem with this payment."
      redirect_to payments_url
    end
  end
  
  
  def destroy
    @payment = Payment.find_by_id(params[:id])
    @payment.destroy
    redirect_to payments_path, notice: 'Payment was successfully deleted.'
  end
  
  
  def alice_step_1
    # Fig. 3, steps 1,2,3,5,7
    # Alice creates 300 values for Tumbler, mixing 15 real values with 285 fake values
    @payment = Payment.find(params[:id])

    if @payment.real_indices.blank?
      real_indices = []
      prng = Random.new
      while real_indices.count < 15
        j = prng.rand(0..299)
        unless real_indices.include? j
          real_indices << j
        end
      end
      @payment.real_indices = real_indices.sort
      @payment.save # save indices of real values to @payment.real_indices
    end

    e = $TUMBLER_RSA_PUBLIC_EXPONENT
    n = $TUMBLER_RSA_PUBLIC_KEY

    salt=Random.new.bytes(128).unpack('H*')[0] # 1024-bit random integer
    puts "Salt: #{salt}"
    @r_values = []
    @ro_values = []

    for i in 0..299  # create 300 blinding factors
      if @payment.real_indices.include? i
        @r_values[i]=Random.new.bytes(10).unpack('H*')[0] # "8f0722a18b63d49e8d9a", size = 20 hex char, 80 bits, 10 bytes
        @ro_values[i] = nil
      else
        # salt is same size as y, otherwise Tumbler can easily tell real values from fake values based on the size of s
        @r_values[i]=(Random.new.bytes(10).unpack('H*')[0].to_i(16)*salt.to_i(16) % n).to_s(16)
        @ro_values[i] = @r_values[i]
      end
    end

    @beta_values = []
    begin
    # first, compute 15 real beta values
      if @payment.valid_y?
        p = @payment.y.to_i(16) # y = epsilon^^pk,received from Bob

        for i in 0..299
          m = @r_values[i].to_i(16)
          if @payment.real_indices.include? i
            b = mod_pow(m,e,n)
            beta_value = (p*b) % n
          else
            beta_value = mod_pow(m,e,n)
          end
          @beta_values[i] = beta_value.to_s(16)
        end
      
        response= RestClient.patch $TUMBLER_PAYMENT_API_URL, {payment: {alice_public_key: @payment.alice_public_key, beta_values: "#{@beta_values}"}}
        result = JSON.parse(response.body)
        @payment.expiry_date = result["expiry_date"]
        # get c values from result params and put them in an array
        @c_values = Array.new
        @c_values = result["c_values"]
        @payment.c_values = @c_values

        # get h values from result params and put them in an array
        @h_values = Array.new
        @h_values = result["h_values"]
        @payment.h_values = @h_values

        @payment.beta_values = @beta_values
        @payment.r_values = @r_values # 15 real r values to be revealed to Tumbler after step 8
        @payment.beta_values_sent # update state from "step1" to "step3"
        @payment.c_h_values_received # update payment state from "step3" to "step5"
        @payment.save
      else
        raise "Before computing beta values, Alice must get y from Bob."
      end
    rescue RuntimeError
      flash[:alert] = "Before computing beta values, Alice must get y from Bob."
      redirect_to payments_url
      return
    end

    # send real indices and 285 (fake) ro values to Tumbler
    # ro values are a 300-element array with 15 nil values in it.
    response= RestClient.patch $TUMBLER_PAYMENT_API_URL, {payment: {alice_public_key: @payment.alice_public_key, real_indices: "#{@payment.real_indices}",ro_values: "#{@ro_values}"}}
    result = JSON.parse(response.body)

    # Fig 3, step 7
    # For 285 fake indices, Alice verifies now that h = H(k), computes s = Dec(k,c) and verifies also that s = ro
    @fake_k_values = Array.new
    @fake_k_values = result["fake_k_values"]

    true_count = 0
    j = 0
    for i in 0..299
      unless @payment.real_indices.include? i
        if @payment.h_values[i] == @fake_k_values[j].ripemd160.to_hex
          true_count += 1
        end
        j += 1
      end
    end

    if true_count != 285
      raise 'Check fake k values failed: mismatch between h and H(k) values.'
    end
    # Alice now computes s = Dec(k,c) and verifies that s^^pk = beta

    @s_values = []
    j = 0
    for i in 0..299
      unless @payment.real_indices.include? i
        key_hex = @fake_k_values[j]
        c = @payment.c_values[i]
        decipher = OpenSSL::Cipher::AES256.new(:CBC)
        decipher.decrypt
        iv_hex = $AES_INIT_VECTOR
        key = key_hex.htb
        iv = iv_hex.htb
        decipher.key = key
        decipher.iv = iv
        @s_values[i] =  decipher.update(BTC::Data.data_from_hex(c)) + decipher.final
        j += 1
      end
    end

    true_count = 0
    for i in 0..299
      unless @payment.real_indices.include? i
        if (@payment.ro_values[i] == @s_values[i])  # verify s = ro (fake values)
          true_count += 1
        end
      end
    end

    if true_count != 285
        puts "Mismatch between fake s and ro values."
        raise 'Tumblebit protocol session aborted: mismatch between fake s and ro values'
    end
    
    # Post transaction Tpuzzle offering 1 bitcoin within timewindow tw1
    # under condition “the fulfilling transaction is signed by T and has preimages of hj ∀j ∈ R”
    
    @payment.k_values = @fake_k_values
    @payment.fake_k_values_checked # update state from "step5" to "step7"
    @payment.y_value_sent # update state from "step7" to "step8"
    @payment.save
    
    # send y and real r_values to Tumbler so he can validate y: Tumbler verifies for all j ∈ R βj=y·(rj)e mod n
    response= RestClient.patch $TUMBLER_PAYMENT_API_URL, {payment: {alice_public_key: @payment.alice_public_key, y: "#{@payment.y}",r_values: "#{@payment.r_values}"}}
    result = JSON.parse(response.body)
    
    flash[:notice] = "Payment successfully updated: step 8 completed. Post transaction Tpuzzle"
    render "show"
    
  end # of method alice_step_1
  
  
  def alice_step_11
    # Learn kj from Tsolve spending Tpuzzle funded by Alice in alice_step_7
    # @payments = Payment.all
    @payment = Payment.find(params[:id])

    # url_string = $BLOCKR_RAW_TX_URL + "#{@payment.first_spending_tx_hash_unconfirmed}"
    # url_string = $BLOCKCHAIN_RAW_TX_URL + "#{@payment.first_spending_tx_hash_unconfirmed}" +"?format=hex"
    url_string = $BLOCKCHAIN_RAW_TX_URL + "#{@payment.first_spending_tx_hash}" +"?format=hex"
    @agent = Mechanize.new
    begin
      page = @agent.get url_string
    rescue Exception => e
      page = e.page
    end
    data = page.body
    # result = JSON.parse(data)
    # @transaction = BTC::Transaction.new(hex: result['data']['tx']['hex'])
    if data.size >= 64
      @transaction = BTC::Transaction.new(hex: data)
      @words = @transaction.dictionary['in'][0]['scriptSig']['asm'].split(/\W+/) # array of real k values revealed by Tumbler
      @real_k_values = []
      for i in 1..15
			  @real_k_values[i-1] = @words[16-i].scan(/../).map { |x| x.hex.chr }.join # convert to hex string
		  end
      # Decrypt cj to sj = Hprg(kj) ⊕ cj
      # Decrypt 15 real cj to sj = Hprg(kj) ⊕ cj 
      @real_s_values = []
      @real_c_values = @payment.real_c_values
      # Tumbler picked 15 real random symetric encryption key k (128 bits) and computed 
      # c = Enc(k, s) and h = H(k)
      true_count = 0
      e = $TUMBLER_RSA_PUBLIC_EXPONENT
      n = $TUMBLER_RSA_PUBLIC_KEY
      for i in 0..14
        decipher = OpenSSL::Cipher::AES256.new(:CBC)
        decipher.decrypt
      
        key_hex = @real_k_values[i]
        iv_hex = $AES_INIT_VECTOR
        key = key_hex.htb
        iv = iv_hex.htb
        decipher.key = key
        decipher.iv = iv
        encrypted = @real_c_values[i].htb

app/views/payments/_form.html.erb
<%= form_for(@payment, multipart: true) do |f| %>
  <div class="field">
    <p><%= f.label 'Title' %></p>
    <p><%= f.text_field :title %></p>
  </div>

</br>
<% unless @payment.y %>
  <div class="field">
    <p><%= f.label 'Puzzle y received from Bob' %></p>
    <p><%= f.text_field :y, :style => "width:840px;", :placeholder => "9868b5efb067748dfbbdaa279f1c47789f2e7ba685f9808675f8916827c4320eee9ad99870636ad8e4d656c3bdcd07a438ac6b1f18a2f0eb1639beb1f83ca21bd929b8551cd28694d4eab2be258d356d8c585c4a594264894d60bf99b66fb0ea1029cc51b56205d2ee150ae1235869e5bb041b4cbf74e831ce4ad27a68707d0" %></p>
  </div>
  <% end %>
</br>
	
	<% if @payment.id %>
		<%= f.submit 'Submit payment puzzle to Tumbler', :class => "btn btn-primary" %>
	<% else %>
		<%= f.submit 'Start payment creation', :class => "btn btn-primary" %>
	<% end %>

<% end %>
</br>
<script>
var ready;
ready = function() {

	var codeSnippet = $('#snippet').data('code');
	var element = document.getElementById("contrat");
	
	var form_field_value = $("#script_category").val()
	
	switch (form_field_value) {

		case "tumblebit_puzzle":
			select = document.getElementById("subFormLine1");
			if (select) {
				select.innerHTML="In the Tumblebit puzzle solving protocol, Alice pays Bob through Tumbler, a trustless intermediary.";
						}
			select = document.getElementById("subFormLine2");
			if (select) {
				select.innerHTML="The script is funded by Alice and can be spent to pay Bob if signed by Tumbler, knowing all ki, pre-images of hi, for i in 1..15.";
						}
			codeSnippet = "IF&#10;RIPEMD160  &#60;h1&#62; EQUALVERIFY&#10;...&#10;RIPEMD160  &#60;h15&#62; EQUALVERIFY&#10;&#60;TumblerPubkey&#62;CHECKSIG&#10;ELSE&#10;&#60;expiry time&#62; CHECKLOCKTIMEVERIFY DROP &#60;AlicePubkey&#62; CHECKSIG&#10;ENDIF";
			break;
		case "tumblebit_escrow_contract":
			select = document.getElementById("subFormLine1");
			if (select) {
				select.innerHTML="A transaction spending from this address cannot be included in a block until the set date and time has passed, unless the 2 required signatures are provided.";
				}
			select = document.getElementById("subFormLine2");
			if (select) {
				select.innerHTML="After the set date and time has passed, the Tumbler's signature is sufficient to move the funds.";
				}
		    codeSnippet = "IF&#10;2 &#60;Tumbler&#62;&#60;Bob&#62; 2 CHECKMULTISIG&#10;ELSE&#10;&#60;expiry time&#62; CHECKLOCKTIMEVERIFY DROP&#10;&#60;Tumbler&#62; CHECKSIG&#10;ENDIF";
		
	}
	element.innerHTML = codeSnippet;
	console.log(codeSnippet);
	console.log(form_field_value);
};

$(document).ready(ready);
</script>

app/views/payments/_payment.html.erb
<td><%= payment.hash_address %></td>
<td><%= payment.aasm_state %></td>
<td><%= link_to payment.alice_public_key, payment %></td>
<td><%= link_to "Edit", edit_payment_path(payment), :class => 'btn btn-xs btn-success' %></td>
<td><%= link_to "Delete", payment_path(payment), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'btn btn-xs btn-danger' %></td>

app/views/payments/alice_step_7.html.erb
<div class="container">
  <div class="row">
	<h3>Tumblebit (Alice) Puzzle # <%= @payment.id %></h3>
	<p>P2SH Address: <strong><%= @payment.hash_address %></strong></p>

	<p>Expiry: <strong><%= Time.at(@payment.expiry_date.to_time.to_i).utc %></strong></br>
	Expiry in seconds since epoch time (1/1/1970): <%= @payment.expiry_date.to_time.to_i %></p>
	
	<p>Puzzle y: <pre style="width:600px"><code><%= @payment.y %></code></pre></p>
	<p>Blinding factors r: <pre style="width:600px"><code><%= @payment.r_values %></code></pre></p>
	<p>Address funded by Alice: <strong><%= BTC::Key.new(wif:@payment.alice_private_key).address.to_s %></strong></p>
	<p>Puzzle Transaction: <pre style="width:600px"><code><%= @payment.puzzle_transaction %></code></pre></p>
		</br>
	
	</div>
</div>

app/views/payments/alice_step_9.html.erb
<div class="container">
  <div class="row">
	<h3>Tumblebit (Alice) Puzzle # <%= @payment.id %></h3>
	<p>P2SH Address: <strong><%= @payment.hash_address %></strong></p>

	<p>Expiry: <strong><%= Time.at(@payment.expiry_date.to_time.to_i).utc %></strong></br>
	Expiry in seconds since epoch time (1/1/1970): <%= @payment.expiry_date.to_time.to_i %></p>
	
	<p>Real k values:</p>
	<% for i in 0..14 %>
		<p><strong><%= @real_k[i] %></strong></p>
	<% end %>
	
		<p>Raw transaction paying Tumbler and containing real k values so Alice gets them when tx is broadcast:</p>
		<pre style="width:600px"><code><%= @payment.signed_tx %></code></pre>
		</br>
	
	</div>
</div>

app/views/payments/create_blinding_factors.html.erb
<div class="container">
  <div class="row">
	<h3>Payment # <%= @payment.id if @script %>: <%= @script.title if @script %></h3>
	<p>P2SH Address: <strong><%= @payment.hash_address if @script %></strong></p>
	<p>Bob's Address (?): <strong><%= @payment.refund_address if @script %></strong></p>

	<p>Expiry: <strong><%= Time.at(@payment.expiry_date.to_time.to_i).utc %></strong></br>
	Expiry in seconds since epoch time (1/1/1970): <%= @payment.expiry_date.to_time.to_i %></p>
	
	<p><%=link_to "Tumbler encrypts values", alice_step_4_payment_path, :class => "btn btn-primary" %></p>
	
	
	
	</div>
</div>

app/views/payments/edit.html.erb
<div class="container">
  <div class="row">
	<h1>Edit Payment # <%= @payment.id if @payment %></h1>

	<%= render 'form' %>

   </div>
</div>

app/views/payments/index.html.erb
<div class="container">
  <div class="row">
    <h3>Payments</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @payments.each do |payment| %>
            <tr>
              <%= render payment %>
            </tr>
          <% end %>
        </tbody>
      </table>
	  <div class="apple_pagination">
		<%= will_paginate @payments %>
	  </div>
    </div>
  </div>
</div>

app/views/payments/new.html.erb
<div class="container">
  <div class="row">
<h3> Send a New Payment</h3>
<%= form_for(@payment, multipart: true) do |f| %>
<p>Alice Public Key: <%= @payment.alice_public_key %></p>
<% @payment.real_indices.each do |real| %>
    <%= f.hidden_field :real_indices, :multiple => true, :value => real %>
<% end %>
<%= f.hidden_field :key_path , :value => @payment.key_path %>
	
	<% if @payment.id %>
		<%= f.submit 'Update payment with parameters', :class => "btn btn-primary" %>
	<% else %>
		<%= f.submit 'Start Payment Process', :class => "btn btn-primary" %>
	<% end %>
	 | <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
        payments_path, :class => 'btn' %>
<% end %>
</br>
	</div>
</div>

app/views/payments/search.html.erb
<div class="container">
  <div class="row">
    <h3> Payments In Progress</h3>
    <div class="column">
		<%= form_tag(posts_path, :method => "get", id: "search-form") do %>
		<%= text_field_tag :search, params[:search], placeholder: "Search Payment by Alice Public Key" %>
		<%= submit_tag "Search" %>
		<% end %>
      <table class="table">
        <tbody>
          <% @payments.each do |payment| %>
            <tr>
              <%= render payment %>
            </tr>
          <% end %>
        </tbody>
      </table>
	  <div class="apple_pagination">
		<%= will_paginate @payments %>
	  </div>
    </div>
  </div>
</div>

app/views/payments/show.html.erb
<div class="container">
  <div class="row">
		<!-- Bitcoin Address Modal -->
		<%= javascript_include_tag 'bootstrap/jquery.qrcode.min.js', 'data-turbolinks-track' => true %>
	
		<div class="modal fade" id="bitcoinModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
		  <div class="modal-dialog" role="document">
		    <div class="modal-content">
		      <div class="modal-header">
		        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		        <h5 class="modal-title" id="myModalLabel">Bitcoin Address to be funded by Alice:</h5>
		      </div>
		      <div class="modal-body">
				<div id="qrcodeCanvas"></div>
		        <strong><%= @payment.hash_address %></strong>
				<script>
					jQuery('#qrcodeCanvas').qrcode({
						text	: '<%= escape_javascript @payment.hash_address.to_s %>'
						
					});	
				</script>
		      </div>
		    </div>
		  </div>
		</div>
		
	<h3>Payment # <%= @payment.id %>: <%= @payment.title %></h3>
	<% unless @payment.aasm_state == "step8"%>
		<p>P2SH Address: <strong><%= @payment.hash_address %></strong></p>
	<% end %>
	<p>Tumbler's Public Key: <strong><%= @payment.tumbler_public_key %></strong></p>
	<p>Alice Public Key: <strong><%= @payment.alice_public_key %></strong></p>

	<p>Expiry: <strong><%= Time.at(@payment.expiry_date.to_time.to_i).utc %></strong></br>
	Expiry in seconds since epoch time (1/1/1970): <%= @payment.expiry_date.to_time.to_i %></p>
	</br>
	<p>Payment State: <strong><%= @payment.aasm_state %></strong></p>
		
	<% if @payment.y.blank? %>
		<%= form_for(@payment, multipart: true) do |f| %>
			<div class="field">
			   <p><%= f.label 'Alice Puzzle Access Code y' %></p>
			   <p><%= f.text_area :y, :class => "form-control", :rows => 2, :placeholder => "b2aeac0d6d50bf63b01522936b9bcf58ef7dd196cefff6ba80d470d125e4f24501cc2305dca1a34e344b59ae1a8251e47a1c2da52fd7630303856cbf729ec0ffe2b27365b3cd49f2e4bbedd2a4b7b4563181a1073e6b099fffb1a9beb5f5710c1afeff06ee38b4250bd069dfc4bcddc47495837272a35268e794e6c5919dc136" %></p>
			 </div>
			
			<%= f.submit 'Start Payment Process with Tumbler', :class => "btn btn-primary" %>
		<% end %>
	<% end %>
	</br>
	<% if @payment.aasm_state == "step8"%>
	<p>Puzzle y: <pre style="width:600px"><code><%= @payment.y %></code></pre></p>
		<% if @payment.first_spending_tx_hash_unconfirmed %>
			<p><%=link_to 'Get puzzle solution', alice_step_11_payment_path(@payment), :class => "btn btn-primary" %> | <%= link_to t('.cancel', :default => t("helpers.links.cancel")), payments_path, :class => 'btn' %></p>
		<% else %>
			<p>Tumbler has not been paid yet. Alice should pay P2SH (escrow) address: 
			<% if !@payment.hash_address.blank? %>
			<a href="#bitcoinModal" data-toggle="modal" title="Bitcoin">
	      <span><i class="fa fa-qrcode fa-lg"></i>      <strong><%= @payment.hash_address %></strong></span></a>
			<% end %></p>
		<% end %>
	<% end %>
	<% if @payment.aasm_state == "completed" %>
	<p>Puzzle y: <pre style="width:600px"><code><%= @payment.y %></code></pre></p>
	<p>Puzzle solution y**d: <pre style="width:600px"><code><%= @payment.solution %></code></pre></p>
	<% end %>
	</br>
	
	
	</div>
</div>

app/views/payments/tumbler_checks_ro_values.html.erb
<div class="container">
  <div class="row">
	<h3>Payment # <%= @payment.id %>: <%= @payment.title %></h3>
	<p>P2SH Address: <strong><%= @payment.hash_address %></strong></p>
	<p>Bob's Address: <strong><%= @payment.refund_address %></strong></p>

	<p>Expiry: <strong><%= Time.at(@payment.expiry_date.to_time.to_i).utc %></strong></br>
	Expiry in seconds since epoch time (1/1/1970): <%= @payment.expiry_date.to_time.to_i %></p>
	
	<p><a href="<%= products_path('kvaluesd4735e.csv') %>" class="btn btn-lg btn-primary heading__btn wow fadeInUp" >Download File with Tumbler 300 k values </a> | <%=link_to "Alice checks Tumbler's k values", sender_checks_k_values_payment_path, :class => "btn btn-primary" %></p>
	
	</div>
</div>