config/routes.rb
Rails.application.routes.draw do
  
  resources :posts
  resources :visitors
  
  match '/contacts',     to: 'contacts#new',             via: 'get'
  match '/contacts',     to: 'contacts#create',          via: 'post'
  resources "contacts", only: [:new, :create]

  get 'posts/index'

  get 'posts/show'
  
  get 'products/:id', to: 'products#show', :as => :products

  resources :users
    
  resources :payments do
    member do
      get 'alice_step_1'
      get 'alice_step_11'
    end
  end
    
  resources :payment_requests do
    member do
      get 'bob_step_2'
      get 'complete'
      patch 'broadcast'
    end
  end
  
  root to: 'visitors#index'
  
  get '/auth/:provider/callback' => 'sessions#create'
  get '/signin' => 'sessions#new', :as => :signin
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/auth/failure' => 'sessions#failure'
  
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>

<nav class="navbar navbar-default navbar-fixed-top js-navbar-top js-toggleClass">
        <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="<%= root_path %>" style="color:#4682b4" onMouseOver="this.style.color='#42aef3'; " onMouseOut="this.style.color='#4682b4'" >Tumblebit.network Wallet</a>
          </div>
          <div id="navbar" class="collapse navbar-collapse">
            <ul class="nav navbar-nav navbar-right ">
              <%= render 'layouts/navigation_links' %>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
  <li><a href="<%= new_payment_request_path %>" style="color:#4682b4" onMouseOver="this.style.color='#42aef3'" onMouseOut="this.style.color='#4682b4'" ><i class="fa fa-arrow-circle-o-down fa-lg" aria-hidden="true"></i> Receive</a></li>
  <li><a href="<%= payment_requests_path %>" style="color:#4682b4" onMouseOver="this.style.color='#42aef3'" onMouseOut="this.style.color='#4682b4'" ><i class="fa fa-list" aria-hidden="true"></i> Payment Requests</a></li>
  <li><a href="<%= new_payment_path %>" style="color:#4682b4" onMouseOver="this.style.color='#42aef3'" onMouseOut="this.style.color='#4682b4'" ><i class="fa fa-paper-plane" aria-hidden="true"></i> Send</a></li>
  <li><a href="<%= payments_path %>" style="color:#4682b4" onMouseOver="this.style.color='#42aef3'" onMouseOut="this.style.color='#4682b4'" ><i class="fa fa-list" aria-hidden="true"></i> Payments</a></li>

  <li><a href="<%= page_path('about') %>" style="color:#4682b4" onMouseOver="this.style.color='#42aef3'" onMouseOut="this.style.color='#4682b4'" ><i class="fa fa-compass fa-lg" aria-hidden="true"></i> About</a></li>

<% if user_signed_in? %>
  <li><a href="<%= signout_path %>" style="color:#4682b4" onMouseOver="this.style.color='#42aef3'" onMouseOut="this.style.color='#4682b4'" >Sign out</a></li>
  <li><a href="<%= users_path %>" style="color:#4682b4" onMouseOver="this.style.color='#42aef3'" onMouseOut="this.style.color='#4682b4'" >Admins</a></li>
<li><a href="<%= clients_path %>" style="color:#4682b4" onMouseOver="this.style.color='#42aef3'" onMouseOut="this.style.color='#4682b4'" >Registrations</a></li>
<% end %>
  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
	<%= favicon_link_tag 'favicon.ico' %>


    <title>Tumblebit Wallet</title>

    <!-- Google Fonts -->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,600,700' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Karla:400,700' rel='stylesheet' type='text/css'>

	<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
	
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'custom', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'plugins/jquery.waypoints.min.js', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'plugins/wow.min.js', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'plugins/owl.carousel.min.js', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'plugins/jquery.peity.min.js', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'plugins/smoothscroll.js', 'data-turbolinks-track' => true %>

    <%= csrf_meta_tags %>
  </head>
  <body data-spy="scroll" data-target=".navbar" data-offset="71">
	<div style="position: fixed; top:0; right:0; z-index: 9999999;"><%= image_tag "beta.png", style: "width:100px;" %></div>
   <div class="wrapper">
    <header>
      <%= render 'layouts/navigation' %>
    </header>

	<div id="fb-root"></div>
	<script>(function(d, s, id) {
	  var js, fjs = d.getElementsByTagName(s)[0];
	  if (d.getElementById(id)) return;
	  js = d.createElement(s); js.id = id;
	  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.3&appId=266016473430241";
	  fjs.parentNode.insertBefore(js, fjs);
	}(document, 'script', 'facebook-jssdk'));</script>
	
    <main role="main" style="padding-top: 100px;">
       <!--<%= render 'layouts/messages' %>-->
	<% if notice %>
	  <p class="alert alert-success"><%= notice %></p>
	<% end %>
	<% if alert %>
	  <p class="alert alert-danger"><%= alert %></p>
	<% end %>
       <%= yield %>
    </main>
   </div>
  </body>
</html>